;;; subst-ari.el --- Unicode to JIS X 0208 Extension translation -*-coding: shift_jis;-*-

;; Copyright (C) 2004  ARISAWA Akihiro

;; Author: ARISAWA Akihiro <ari@mbf.sphere.ne.jp>
;; Keywords: i18n

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

;;; Commentary:

;; Provides translation tables between Unicode and JIS X 0208 Extension
;; charsets (NEC special characters & NEC selection of IBM extension
;; characters).

;; Put following lines to your .emacs.

;; (eval-after-load "subst-jis" '(load "subst-jisx0208ex"))

;;; Code:

(mapc
 (lambda (pair)
   (let ((unicode (car pair))
	 (char (cadr pair)))
     (puthash unicode  char ucs-unicode-to-mule-cjk)
     (puthash char unicode ucs-mule-cjk-to-unicode)))
 '(
   ;; NEC special characters
   (#x2460 ?á@) ; CIRCLED DIGIT ONE
   (#x2461 ?áA) ; CIRCLED DIGIT TWO
   (#x2462 ?áB) ; CIRCLED DIGIT THREE
   (#x2463 ?áC) ; CIRCLED DIGIT FOUR
   (#x2464 ?áD) ; CIRCLED DIGIT FIVE
   (#x2465 ?áE) ; CIRCLED DIGIT SIX
   (#x2466 ?áF) ; CIRCLED DIGIT SEVEN
   (#x2467 ?áG) ; CIRCLED DIGIT EIGHT
   (#x2468 ?áH) ; CIRCLED DIGIT NINE
   (#x2469 ?áI) ; CIRCLED NUMBER TEN
   (#x246A ?áJ) ; CIRCLED NUMBER ELEVEN
   (#x246B ?áK) ; CIRCLED NUMBER TWELVE
   (#x246C ?áL) ; CIRCLED NUMBER THIRTEEN
   (#x246D ?áM) ; CIRCLED NUMBER FOURTEEN
   (#x246E ?áN) ; CIRCLED NUMBER FIFTEEN
   (#x246F ?áO) ; CIRCLED NUMBER SIXTEEN
   (#x2470 ?áP) ; CIRCLED NUMBER SEVENTEEN
   (#x2471 ?áQ) ; CIRCLED NUMBER EIGHTEEN
   (#x2472 ?áR) ; CIRCLED NUMBER NINETEEN
   (#x2473 ?áS) ; CIRCLED NUMBER TWENTY
   (#x2160 ?áT) ; ROMAN NUMERAL ONE
   (#x2161 ?áU) ; ROMAN NUMERAL TWO
   (#x2162 ?áV) ; ROMAN NUMERAL THREE
   (#x2163 ?áW) ; ROMAN NUMERAL FOUR
   (#x2164 ?áX) ; ROMAN NUMERAL FIVE
   (#x2165 ?áY) ; ROMAN NUMERAL SIX
   (#x2166 ?áZ) ; ROMAN NUMERAL SEVEN
   (#x2167 ?á[) ; ROMAN NUMERAL EIGHT
   (#x2168 ?á\) ; ROMAN NUMERAL NINE
   (#x2169 ?á]) ; ROMAN NUMERAL TEN
   (#x3349 ?á_) ; SQUARE MIRI
   (#x3314 ?á`) ; SQUARE KIRO
   (#x3322 ?áa) ; SQUARE SENTI
   (#x334D ?áb) ; SQUARE MEETORU
   (#x3318 ?ác) ; SQUARE GURAMU
   (#x3327 ?ád) ; SQUARE TON
   (#x3303 ?áe) ; SQUARE AARU
   (#x3336 ?áf) ; SQUARE HEKUTAARU
   (#x3351 ?ág) ; SQUARE RITTORU
   (#x3357 ?áh) ; SQUARE WATTO
   (#x330D ?ái) ; SQUARE KARORII
   (#x3326 ?áj) ; SQUARE DORU
   (#x3323 ?ák) ; SQUARE SENTO
   (#x332B ?ál) ; SQUARE PAASENTO
   (#x334A ?ám) ; SQUARE MIRIBAARU
   (#x333B ?án) ; SQUARE PEEZI
   (#x339C ?áo) ; SQUARE MM
   (#x339D ?áp) ; SQUARE CM
   (#x339E ?áq) ; SQUARE KM
   (#x338E ?ár) ; SQUARE MG
   (#x338F ?ás) ; SQUARE KG
   (#x33C4 ?át) ; SQUARE CC
   (#x33A1 ?áu) ; SQUARE M SQUARED
   (#x337B ?á~) ; SQUARE ERA NAME HEISEI
   (#x301D ?áÄ) ; REVERSED DOUBLE PRIME QUOTATION MARK
   (#x301F ?áÅ) ; LOW DOUBLE PRIME QUOTATION MARK
   (#x2116 ?áÇ) ; NUMERO SIGN
   (#x33CD ?áÉ) ; SQUARE KK
   (#x2121 ?áÑ) ; TELEPHONE SIGN
   (#x32A4 ?áÖ) ; CIRCLED IDEOGRAPH HIGH
   (#x32A5 ?áÜ) ; CIRCLED IDEOGRAPH CENTRE
   (#x32A6 ?áá) ; CIRCLED IDEOGRAPH LOW
   (#x32A7 ?áà) ; CIRCLED IDEOGRAPH LEFT
   (#x32A8 ?áâ) ; CIRCLED IDEOGRAPH RIGHT
   (#x3231 ?áä) ; PARENTHESIZED IDEOGRAPH STOCK
   (#x3232 ?áã) ; PARENTHESIZED IDEOGRAPH HAVE
   (#x3239 ?áå) ; PARENTHESIZED IDEOGRAPH REPRESENT
   (#x337E ?áç) ; SQUARE ERA NAME MEIZI
   (#x337D ?áé) ; SQUARE ERA NAME TAISYOU
   (#x337C ?áè) ; SQUARE ERA NAME SYOUWA
   (#x2252 ?áê) ; APPROXIMATELY EQUAL TO OR THE IMAGE OF
   (#x2261 ?áë) ; IDENTICAL TO
   (#x222B ?áí) ; INTEGRAL
   (#x222E ?áì) ; CONTOUR INTEGRAL
   (#x2211 ?áî) ; N-ARY SUMMATION
   (#x221A ?áï) ; SQUARE ROOT
   (#x22A5 ?áñ) ; UP TACK
   (#x2220 ?áó) ; ANGLE
   (#x221F ?áò) ; RIGHT ANGLE
   (#x22BF ?áô) ; RIGHT TRIANGLE
   (#x2235 ?áö) ; BECAUSE
   (#x2229 ?áõ) ; INTERSECTION
   (#x222A ?áú) ; UNION
   ;; NEC selection of IBM extension characters
   (#x7E8A ?Ì@) ; CJK UNIFIED IDEOGRAPH
   (#x891C ?ÌA) ; CJK UNIFIED IDEOGRAPH
   (#x9348 ?ÌB) ; CJK UNIFIED IDEOGRAPH
   (#x9288 ?ÌC) ; CJK UNIFIED IDEOGRAPH
   (#x84DC ?ÌD) ; CJK UNIFIED IDEOGRAPH
   (#x4FC9 ?ÌE) ; CJK UNIFIED IDEOGRAPH
   (#x70BB ?ÌF) ; CJK UNIFIED IDEOGRAPH
   (#x6631 ?ÌG) ; CJK UNIFIED IDEOGRAPH
   (#x68C8 ?ÌH) ; CJK UNIFIED IDEOGRAPH
   (#x92F9 ?ÌI) ; CJK UNIFIED IDEOGRAPH
   (#x66FB ?ÌJ) ; CJK UNIFIED IDEOGRAPH
   (#x5F45 ?ÌK) ; CJK UNIFIED IDEOGRAPH
   (#x4E28 ?ÌL) ; CJK UNIFIED IDEOGRAPH
   (#x4EE1 ?ÌM) ; CJK UNIFIED IDEOGRAPH
   (#x4EFC ?ÌN) ; CJK UNIFIED IDEOGRAPH
   (#x4F00 ?ÌO) ; CJK UNIFIED IDEOGRAPH
   (#x4F03 ?ÌP) ; CJK UNIFIED IDEOGRAPH
   (#x4F39 ?ÌQ) ; CJK UNIFIED IDEOGRAPH
   (#x4F56 ?ÌR) ; CJK UNIFIED IDEOGRAPH
   (#x4F92 ?ÌS) ; CJK UNIFIED IDEOGRAPH
   (#x4F8A ?ÌT) ; CJK UNIFIED IDEOGRAPH
   (#x4F9A ?ÌU) ; CJK UNIFIED IDEOGRAPH
   (#x4F94 ?ÌV) ; CJK UNIFIED IDEOGRAPH
   (#x4FCD ?ÌW) ; CJK UNIFIED IDEOGRAPH
   (#x5040 ?ÌX) ; CJK UNIFIED IDEOGRAPH
   (#x5022 ?ÌY) ; CJK UNIFIED IDEOGRAPH
   (#x4FFF ?ÌZ) ; CJK UNIFIED IDEOGRAPH
   (#x501E ?Ì[) ; CJK UNIFIED IDEOGRAPH
   (#x5046 ?Ì\) ; CJK UNIFIED IDEOGRAPH
   (#x5070 ?Ì]) ; CJK UNIFIED IDEOGRAPH
   (#x5042 ?Ì^) ; CJK UNIFIED IDEOGRAPH
   (#x5094 ?Ì_) ; CJK UNIFIED IDEOGRAPH
   (#x50F4 ?Ì`) ; CJK UNIFIED IDEOGRAPH
   (#x50D8 ?Ìa) ; CJK UNIFIED IDEOGRAPH
   (#x514A ?Ìb) ; CJK UNIFIED IDEOGRAPH
   (#x5164 ?Ìc) ; CJK UNIFIED IDEOGRAPH
   (#x519D ?Ìd) ; CJK UNIFIED IDEOGRAPH
   (#x51BE ?Ìe) ; CJK UNIFIED IDEOGRAPH
   (#x51EC ?Ìf) ; CJK UNIFIED IDEOGRAPH
   (#x5215 ?Ìg) ; CJK UNIFIED IDEOGRAPH
   (#x529C ?Ìh) ; CJK UNIFIED IDEOGRAPH
   (#x52A6 ?Ìi) ; CJK UNIFIED IDEOGRAPH
   (#x52C0 ?Ìj) ; CJK UNIFIED IDEOGRAPH
   (#x52DB ?Ìk) ; CJK UNIFIED IDEOGRAPH
   (#x5300 ?Ìl) ; CJK UNIFIED IDEOGRAPH
   (#x5307 ?Ìm) ; CJK UNIFIED IDEOGRAPH
   (#x5324 ?Ìn) ; CJK UNIFIED IDEOGRAPH
   (#x5372 ?Ìo) ; CJK UNIFIED IDEOGRAPH
   (#x5393 ?Ìp) ; CJK UNIFIED IDEOGRAPH
   (#x53B2 ?Ìq) ; CJK UNIFIED IDEOGRAPH
   (#x53DD ?Ìr) ; CJK UNIFIED IDEOGRAPH
   (#xFA0E ?Ìs) ; CJK COMPATIBILITY IDEOGRAPH
   (#x549C ?Ìt) ; CJK UNIFIED IDEOGRAPH
   (#x548A ?Ìu) ; CJK UNIFIED IDEOGRAPH
   (#x54A9 ?Ìv) ; CJK UNIFIED IDEOGRAPH
   (#x54FF ?Ìw) ; CJK UNIFIED IDEOGRAPH
   (#x5586 ?Ìx) ; CJK UNIFIED IDEOGRAPH
   (#x5759 ?Ìy) ; CJK UNIFIED IDEOGRAPH
   (#x5765 ?Ìz) ; CJK UNIFIED IDEOGRAPH
   (#x57AC ?Ì{) ; CJK UNIFIED IDEOGRAPH
   (#x57C8 ?Ì|) ; CJK UNIFIED IDEOGRAPH
   (#x57C7 ?Ì}) ; CJK UNIFIED IDEOGRAPH
   (#xFA0F ?Ì~) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA10 ?ÌÄ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x589E ?ÌÅ) ; CJK UNIFIED IDEOGRAPH
   (#x58B2 ?ÌÇ) ; CJK UNIFIED IDEOGRAPH
   (#x590B ?ÌÉ) ; CJK UNIFIED IDEOGRAPH
   (#x5953 ?ÌÑ) ; CJK UNIFIED IDEOGRAPH
   (#x595B ?ÌÖ) ; CJK UNIFIED IDEOGRAPH
   (#x595D ?ÌÜ) ; CJK UNIFIED IDEOGRAPH
   (#x5963 ?Ìá) ; CJK UNIFIED IDEOGRAPH
   (#x59A4 ?Ìà) ; CJK UNIFIED IDEOGRAPH
   (#x59BA ?Ìâ) ; CJK UNIFIED IDEOGRAPH
   (#x5B56 ?Ìä) ; CJK UNIFIED IDEOGRAPH
   (#x5BC0 ?Ìã) ; CJK UNIFIED IDEOGRAPH
   (#x752F ?Ìå) ; CJK UNIFIED IDEOGRAPH
   (#x5BD8 ?Ìç) ; CJK UNIFIED IDEOGRAPH
   (#x5BEC ?Ìé) ; CJK UNIFIED IDEOGRAPH
   (#x5C1E ?Ìè) ; CJK UNIFIED IDEOGRAPH
   (#x5CA6 ?Ìê) ; CJK UNIFIED IDEOGRAPH
   (#x5CBA ?Ìë) ; CJK UNIFIED IDEOGRAPH
   (#x5CF5 ?Ìí) ; CJK UNIFIED IDEOGRAPH
   (#x5D27 ?Ìì) ; CJK UNIFIED IDEOGRAPH
   (#x5D53 ?Ìî) ; CJK UNIFIED IDEOGRAPH
   (#xFA11 ?Ìï) ; CJK COMPATIBILITY IDEOGRAPH
   (#x5D42 ?Ìñ) ; CJK UNIFIED IDEOGRAPH
   (#x5D6D ?Ìó) ; CJK UNIFIED IDEOGRAPH
   (#x5DB8 ?Ìò) ; CJK UNIFIED IDEOGRAPH
   (#x5DB9 ?Ìô) ; CJK UNIFIED IDEOGRAPH
   (#x5DD0 ?Ìö) ; CJK UNIFIED IDEOGRAPH
   (#x5F21 ?Ìõ) ; CJK UNIFIED IDEOGRAPH
   (#x5F34 ?Ìú) ; CJK UNIFIED IDEOGRAPH
   (#x5F67 ?Ìù) ; CJK UNIFIED IDEOGRAPH
   (#x5FB7 ?Ìû) ; CJK UNIFIED IDEOGRAPH
   (#x5FDE ?Ìü) ; CJK UNIFIED IDEOGRAPH
   (#x605D ?Ì†) ; CJK UNIFIED IDEOGRAPH
   (#x6085 ?Ì°) ; CJK UNIFIED IDEOGRAPH
   (#x608A ?Ì¢) ; CJK UNIFIED IDEOGRAPH
   (#x60DE ?Ì£) ; CJK UNIFIED IDEOGRAPH
   (#x60D5 ?Ì§) ; CJK UNIFIED IDEOGRAPH
   (#x6120 ?Ì•) ; CJK UNIFIED IDEOGRAPH
   (#x60F2 ?Ì¶) ; CJK UNIFIED IDEOGRAPH
   (#x6111 ?Ìß) ; CJK UNIFIED IDEOGRAPH
   (#x6137 ?Ì®) ; CJK UNIFIED IDEOGRAPH
   (#x6130 ?Ì©) ; CJK UNIFIED IDEOGRAPH
   (#x6198 ?Ì™) ; CJK UNIFIED IDEOGRAPH
   (#x6213 ?Ì´) ; CJK UNIFIED IDEOGRAPH
   (#x62A6 ?Ì¨) ; CJK UNIFIED IDEOGRAPH
   (#x63F5 ?Ì≠) ; CJK UNIFIED IDEOGRAPH
   (#x6460 ?ÌÆ) ; CJK UNIFIED IDEOGRAPH
   (#x649D ?ÌØ) ; CJK UNIFIED IDEOGRAPH
   (#x64CE ?Ì∞) ; CJK UNIFIED IDEOGRAPH
   (#x654E ?Ì±) ; CJK UNIFIED IDEOGRAPH
   (#x6600 ?Ì≤) ; CJK UNIFIED IDEOGRAPH
   (#x6615 ?Ì≥) ; CJK UNIFIED IDEOGRAPH
   (#x663B ?Ì¥) ; CJK UNIFIED IDEOGRAPH
   (#x6609 ?Ìµ) ; CJK UNIFIED IDEOGRAPH
   (#x662E ?Ì∂) ; CJK UNIFIED IDEOGRAPH
   (#x661E ?Ì∑) ; CJK UNIFIED IDEOGRAPH
   (#x6624 ?Ì∏) ; CJK UNIFIED IDEOGRAPH
   (#x6665 ?Ìπ) ; CJK UNIFIED IDEOGRAPH
   (#x6657 ?Ì∫) ; CJK UNIFIED IDEOGRAPH
   (#x6659 ?Ìª) ; CJK UNIFIED IDEOGRAPH
   (#xFA12 ?Ìº) ; CJK COMPATIBILITY IDEOGRAPH
   (#x6673 ?ÌΩ) ; CJK UNIFIED IDEOGRAPH
   (#x6699 ?Ìæ) ; CJK UNIFIED IDEOGRAPH
   (#x66A0 ?Ìø) ; CJK UNIFIED IDEOGRAPH
   (#x66B2 ?Ì¿) ; CJK UNIFIED IDEOGRAPH
   (#x66BF ?Ì¡) ; CJK UNIFIED IDEOGRAPH
   (#x66FA ?Ì¬) ; CJK UNIFIED IDEOGRAPH
   (#x670E ?Ì√) ; CJK UNIFIED IDEOGRAPH
   (#xF929 ?Ìƒ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x6766 ?Ì≈) ; CJK UNIFIED IDEOGRAPH
   (#x67BB ?Ì∆) ; CJK UNIFIED IDEOGRAPH
   (#x6852 ?Ì«) ; CJK UNIFIED IDEOGRAPH
   (#x67C0 ?Ì») ; CJK UNIFIED IDEOGRAPH
   (#x6801 ?Ì…) ; CJK UNIFIED IDEOGRAPH
   (#x6844 ?Ì ) ; CJK UNIFIED IDEOGRAPH
   (#x68CF ?ÌÀ) ; CJK UNIFIED IDEOGRAPH
   (#xFA13 ?ÌÃ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x6968 ?ÌÕ) ; CJK UNIFIED IDEOGRAPH
   (#xFA14 ?ÌŒ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x6998 ?Ìœ) ; CJK UNIFIED IDEOGRAPH
   (#x69E2 ?Ì–) ; CJK UNIFIED IDEOGRAPH
   (#x6A30 ?Ì—) ; CJK UNIFIED IDEOGRAPH
   (#x6A6B ?Ì“) ; CJK UNIFIED IDEOGRAPH
   (#x6A46 ?Ì”) ; CJK UNIFIED IDEOGRAPH
   (#x6A73 ?Ì‘) ; CJK UNIFIED IDEOGRAPH
   (#x6A7E ?Ì’) ; CJK UNIFIED IDEOGRAPH
   (#x6AE2 ?Ì÷) ; CJK UNIFIED IDEOGRAPH
   (#x6AE4 ?Ì◊) ; CJK UNIFIED IDEOGRAPH
   (#x6BD6 ?Ìÿ) ; CJK UNIFIED IDEOGRAPH
   (#x6C3F ?ÌŸ) ; CJK UNIFIED IDEOGRAPH
   (#x6C5C ?Ì⁄) ; CJK UNIFIED IDEOGRAPH
   (#x6C86 ?Ì€) ; CJK UNIFIED IDEOGRAPH
   (#x6C6F ?Ì‹) ; CJK UNIFIED IDEOGRAPH
   (#x6CDA ?Ì›) ; CJK UNIFIED IDEOGRAPH
   (#x6D04 ?Ìﬁ) ; CJK UNIFIED IDEOGRAPH
   (#x6D87 ?Ìﬂ) ; CJK UNIFIED IDEOGRAPH
   (#x6D6F ?Ì‡) ; CJK UNIFIED IDEOGRAPH
   (#x6D96 ?Ì·) ; CJK UNIFIED IDEOGRAPH
   (#x6DAC ?Ì‚) ; CJK UNIFIED IDEOGRAPH
   (#x6DCF ?Ì„) ; CJK UNIFIED IDEOGRAPH
   (#x6DF8 ?Ì‰) ; CJK UNIFIED IDEOGRAPH
   (#x6DF2 ?ÌÂ) ; CJK UNIFIED IDEOGRAPH
   (#x6DFC ?ÌÊ) ; CJK UNIFIED IDEOGRAPH
   (#x6E39 ?ÌÁ) ; CJK UNIFIED IDEOGRAPH
   (#x6E5C ?ÌË) ; CJK UNIFIED IDEOGRAPH
   (#x6E27 ?ÌÈ) ; CJK UNIFIED IDEOGRAPH
   (#x6E3C ?ÌÍ) ; CJK UNIFIED IDEOGRAPH
   (#x6EBF ?ÌÎ) ; CJK UNIFIED IDEOGRAPH
   (#x6F88 ?ÌÏ) ; CJK UNIFIED IDEOGRAPH
   (#x6FB5 ?ÌÌ) ; CJK UNIFIED IDEOGRAPH
   (#x6FF5 ?ÌÓ) ; CJK UNIFIED IDEOGRAPH
   (#x7005 ?ÌÔ) ; CJK UNIFIED IDEOGRAPH
   (#x7007 ?Ì) ; CJK UNIFIED IDEOGRAPH
   (#x7028 ?ÌÒ) ; CJK UNIFIED IDEOGRAPH
   (#x7085 ?ÌÚ) ; CJK UNIFIED IDEOGRAPH
   (#x70AB ?ÌÛ) ; CJK UNIFIED IDEOGRAPH
   (#x710F ?ÌÙ) ; CJK UNIFIED IDEOGRAPH
   (#x7104 ?Ìı) ; CJK UNIFIED IDEOGRAPH
   (#x715C ?Ìˆ) ; CJK UNIFIED IDEOGRAPH
   (#x7146 ?Ì˜) ; CJK UNIFIED IDEOGRAPH
   (#x7147 ?Ì¯) ; CJK UNIFIED IDEOGRAPH
   (#xFA15 ?Ì˘) ; CJK COMPATIBILITY IDEOGRAPH
   (#x71C1 ?Ì˙) ; CJK UNIFIED IDEOGRAPH
   (#x71FE ?Ì˚) ; CJK UNIFIED IDEOGRAPH
   (#x72B1 ?Ì¸) ; CJK UNIFIED IDEOGRAPH
   (#x72BE ?Ó@) ; CJK UNIFIED IDEOGRAPH
   (#x7324 ?ÓA) ; CJK UNIFIED IDEOGRAPH
   (#xFA16 ?ÓB) ; CJK COMPATIBILITY IDEOGRAPH
   (#x7377 ?ÓC) ; CJK UNIFIED IDEOGRAPH
   (#x73BD ?ÓD) ; CJK UNIFIED IDEOGRAPH
   (#x73C9 ?ÓE) ; CJK UNIFIED IDEOGRAPH
   (#x73D6 ?ÓF) ; CJK UNIFIED IDEOGRAPH
   (#x73E3 ?ÓG) ; CJK UNIFIED IDEOGRAPH
   (#x73D2 ?ÓH) ; CJK UNIFIED IDEOGRAPH
   (#x7407 ?ÓI) ; CJK UNIFIED IDEOGRAPH
   (#x73F5 ?ÓJ) ; CJK UNIFIED IDEOGRAPH
   (#x7426 ?ÓK) ; CJK UNIFIED IDEOGRAPH
   (#x742A ?ÓL) ; CJK UNIFIED IDEOGRAPH
   (#x7429 ?ÓM) ; CJK UNIFIED IDEOGRAPH
   (#x742E ?ÓN) ; CJK UNIFIED IDEOGRAPH
   (#x7462 ?ÓO) ; CJK UNIFIED IDEOGRAPH
   (#x7489 ?ÓP) ; CJK UNIFIED IDEOGRAPH
   (#x749F ?ÓQ) ; CJK UNIFIED IDEOGRAPH
   (#x7501 ?ÓR) ; CJK UNIFIED IDEOGRAPH
   (#x756F ?ÓS) ; CJK UNIFIED IDEOGRAPH
   (#x7682 ?ÓT) ; CJK UNIFIED IDEOGRAPH
   (#x769C ?ÓU) ; CJK UNIFIED IDEOGRAPH
   (#x769E ?ÓV) ; CJK UNIFIED IDEOGRAPH
   (#x769B ?ÓW) ; CJK UNIFIED IDEOGRAPH
   (#x76A6 ?ÓX) ; CJK UNIFIED IDEOGRAPH
   (#xFA17 ?ÓY) ; CJK COMPATIBILITY IDEOGRAPH
   (#x7746 ?ÓZ) ; CJK UNIFIED IDEOGRAPH
   (#x52AF ?Ó[) ; CJK UNIFIED IDEOGRAPH
   (#x7821 ?Ó\) ; CJK UNIFIED IDEOGRAPH
   (#x784E ?Ó]) ; CJK UNIFIED IDEOGRAPH
   (#x7864 ?Ó^) ; CJK UNIFIED IDEOGRAPH
   (#x787A ?Ó_) ; CJK UNIFIED IDEOGRAPH
   (#x7930 ?Ó`) ; CJK UNIFIED IDEOGRAPH
   (#xFA18 ?Óa) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA19 ?Ób) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA1A ?Óc) ; CJK COMPATIBILITY IDEOGRAPH
   (#x7994 ?Ód) ; CJK UNIFIED IDEOGRAPH
   (#xFA1B ?Óe) ; CJK COMPATIBILITY IDEOGRAPH
   (#x799B ?Óf) ; CJK UNIFIED IDEOGRAPH
   (#x7AD1 ?Óg) ; CJK UNIFIED IDEOGRAPH
   (#x7AE7 ?Óh) ; CJK UNIFIED IDEOGRAPH
   (#xFA1C ?Ói) ; CJK COMPATIBILITY IDEOGRAPH
   (#x7AEB ?Ój) ; CJK UNIFIED IDEOGRAPH
   (#x7B9E ?Ók) ; CJK UNIFIED IDEOGRAPH
   (#xFA1D ?Ól) ; CJK COMPATIBILITY IDEOGRAPH
   (#x7D48 ?Óm) ; CJK UNIFIED IDEOGRAPH
   (#x7D5C ?Ón) ; CJK UNIFIED IDEOGRAPH
   (#x7DB7 ?Óo) ; CJK UNIFIED IDEOGRAPH
   (#x7DA0 ?Óp) ; CJK UNIFIED IDEOGRAPH
   (#x7DD6 ?Óq) ; CJK UNIFIED IDEOGRAPH
   (#x7E52 ?Ór) ; CJK UNIFIED IDEOGRAPH
   (#x7F47 ?Ós) ; CJK UNIFIED IDEOGRAPH
   (#x7FA1 ?Ót) ; CJK UNIFIED IDEOGRAPH
   (#xFA1E ?Óu) ; CJK COMPATIBILITY IDEOGRAPH
   (#x8301 ?Óv) ; CJK UNIFIED IDEOGRAPH
   (#x8362 ?Ów) ; CJK UNIFIED IDEOGRAPH
   (#x837F ?Óx) ; CJK UNIFIED IDEOGRAPH
   (#x83C7 ?Óy) ; CJK UNIFIED IDEOGRAPH
   (#x83F6 ?Óz) ; CJK UNIFIED IDEOGRAPH
   (#x8448 ?Ó{) ; CJK UNIFIED IDEOGRAPH
   (#x84B4 ?Ó|) ; CJK UNIFIED IDEOGRAPH
   (#x8553 ?Ó}) ; CJK UNIFIED IDEOGRAPH
   (#x8559 ?Ó~) ; CJK UNIFIED IDEOGRAPH
   (#x856B ?ÓÄ) ; CJK UNIFIED IDEOGRAPH
   (#xFA1F ?ÓÅ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x85B0 ?ÓÇ) ; CJK UNIFIED IDEOGRAPH
   (#xFA20 ?ÓÉ) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA21 ?ÓÑ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x8807 ?ÓÖ) ; CJK UNIFIED IDEOGRAPH
   (#x88F5 ?ÓÜ) ; CJK UNIFIED IDEOGRAPH
   (#x8A12 ?Óá) ; CJK UNIFIED IDEOGRAPH
   (#x8A37 ?Óà) ; CJK UNIFIED IDEOGRAPH
   (#x8A79 ?Óâ) ; CJK UNIFIED IDEOGRAPH
   (#x8AA7 ?Óä) ; CJK UNIFIED IDEOGRAPH
   (#x8ABE ?Óã) ; CJK UNIFIED IDEOGRAPH
   (#x8ADF ?Óå) ; CJK UNIFIED IDEOGRAPH
   (#xFA22 ?Óç) ; CJK COMPATIBILITY IDEOGRAPH
   (#x8AF6 ?Óé) ; CJK UNIFIED IDEOGRAPH
   (#x8B53 ?Óè) ; CJK UNIFIED IDEOGRAPH
   (#x8B7F ?Óê) ; CJK UNIFIED IDEOGRAPH
   (#x8CF0 ?Óë) ; CJK UNIFIED IDEOGRAPH
   (#x8CF4 ?Óí) ; CJK UNIFIED IDEOGRAPH
   (#x8D12 ?Óì) ; CJK UNIFIED IDEOGRAPH
   (#x8D76 ?Óî) ; CJK UNIFIED IDEOGRAPH
   (#xFA23 ?Óï) ; CJK COMPATIBILITY IDEOGRAPH
   (#x8ECF ?Óñ) ; CJK UNIFIED IDEOGRAPH
   (#xFA24 ?Óó) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA25 ?Óò) ; CJK COMPATIBILITY IDEOGRAPH
   (#x9067 ?Óô) ; CJK UNIFIED IDEOGRAPH
   (#x90DE ?Óö) ; CJK UNIFIED IDEOGRAPH
   (#xFA26 ?Óõ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x9115 ?Óú) ; CJK UNIFIED IDEOGRAPH
   (#x9127 ?Óù) ; CJK UNIFIED IDEOGRAPH
   (#x91DA ?Óû) ; CJK UNIFIED IDEOGRAPH
   (#x91D7 ?Óü) ; CJK UNIFIED IDEOGRAPH
   (#x91DE ?Ó†) ; CJK UNIFIED IDEOGRAPH
   (#x91ED ?Ó°) ; CJK UNIFIED IDEOGRAPH
   (#x91EE ?Ó¢) ; CJK UNIFIED IDEOGRAPH
   (#x91E4 ?Ó£) ; CJK UNIFIED IDEOGRAPH
   (#x91E5 ?Ó§) ; CJK UNIFIED IDEOGRAPH
   (#x9206 ?Ó•) ; CJK UNIFIED IDEOGRAPH
   (#x9210 ?Ó¶) ; CJK UNIFIED IDEOGRAPH
   (#x920A ?Óß) ; CJK UNIFIED IDEOGRAPH
   (#x923A ?Ó®) ; CJK UNIFIED IDEOGRAPH
   (#x9240 ?Ó©) ; CJK UNIFIED IDEOGRAPH
   (#x923C ?Ó™) ; CJK UNIFIED IDEOGRAPH
   (#x924E ?Ó´) ; CJK UNIFIED IDEOGRAPH
   (#x9259 ?Ó¨) ; CJK UNIFIED IDEOGRAPH
   (#x9251 ?Ó≠) ; CJK UNIFIED IDEOGRAPH
   (#x9239 ?ÓÆ) ; CJK UNIFIED IDEOGRAPH
   (#x9267 ?ÓØ) ; CJK UNIFIED IDEOGRAPH
   (#x92A7 ?Ó∞) ; CJK UNIFIED IDEOGRAPH
   (#x9277 ?Ó±) ; CJK UNIFIED IDEOGRAPH
   (#x9278 ?Ó≤) ; CJK UNIFIED IDEOGRAPH
   (#x92E7 ?Ó≥) ; CJK UNIFIED IDEOGRAPH
   (#x92D7 ?Ó¥) ; CJK UNIFIED IDEOGRAPH
   (#x92D9 ?Óµ) ; CJK UNIFIED IDEOGRAPH
   (#x92D0 ?Ó∂) ; CJK UNIFIED IDEOGRAPH
   (#xFA27 ?Ó∑) ; CJK COMPATIBILITY IDEOGRAPH
   (#x92D5 ?Ó∏) ; CJK UNIFIED IDEOGRAPH
   (#x92E0 ?Óπ) ; CJK UNIFIED IDEOGRAPH
   (#x92D3 ?Ó∫) ; CJK UNIFIED IDEOGRAPH
   (#x9325 ?Óª) ; CJK UNIFIED IDEOGRAPH
   (#x9321 ?Óº) ; CJK UNIFIED IDEOGRAPH
   (#x92FB ?ÓΩ) ; CJK UNIFIED IDEOGRAPH
   (#xFA28 ?Óæ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x931E ?Óø) ; CJK UNIFIED IDEOGRAPH
   (#x92FF ?Ó¿) ; CJK UNIFIED IDEOGRAPH
   (#x931D ?Ó¡) ; CJK UNIFIED IDEOGRAPH
   (#x9302 ?Ó¬) ; CJK UNIFIED IDEOGRAPH
   (#x9370 ?Ó√) ; CJK UNIFIED IDEOGRAPH
   (#x9357 ?Óƒ) ; CJK UNIFIED IDEOGRAPH
   (#x93A4 ?Ó≈) ; CJK UNIFIED IDEOGRAPH
   (#x93C6 ?Ó∆) ; CJK UNIFIED IDEOGRAPH
   (#x93DE ?Ó«) ; CJK UNIFIED IDEOGRAPH
   (#x93F8 ?Ó») ; CJK UNIFIED IDEOGRAPH
   (#x9431 ?Ó…) ; CJK UNIFIED IDEOGRAPH
   (#x9445 ?Ó ) ; CJK UNIFIED IDEOGRAPH
   (#x9448 ?ÓÀ) ; CJK UNIFIED IDEOGRAPH
   (#x9592 ?ÓÃ) ; CJK UNIFIED IDEOGRAPH
   (#xF9DC ?ÓÕ) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA29 ?ÓŒ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x969D ?Óœ) ; CJK UNIFIED IDEOGRAPH
   (#x96AF ?Ó–) ; CJK UNIFIED IDEOGRAPH
   (#x9733 ?Ó—) ; CJK UNIFIED IDEOGRAPH
   (#x973B ?Ó“) ; CJK UNIFIED IDEOGRAPH
   (#x9743 ?Ó”) ; CJK UNIFIED IDEOGRAPH
   (#x974D ?Ó‘) ; CJK UNIFIED IDEOGRAPH
   (#x974F ?Ó’) ; CJK UNIFIED IDEOGRAPH
   (#x9751 ?Ó÷) ; CJK UNIFIED IDEOGRAPH
   (#x9755 ?Ó◊) ; CJK UNIFIED IDEOGRAPH
   (#x9857 ?Óÿ) ; CJK UNIFIED IDEOGRAPH
   (#x9865 ?ÓŸ) ; CJK UNIFIED IDEOGRAPH
   (#xFA2A ?Ó⁄) ; CJK COMPATIBILITY IDEOGRAPH
   (#xFA2B ?Ó€) ; CJK COMPATIBILITY IDEOGRAPH
   (#x9927 ?Ó‹) ; CJK UNIFIED IDEOGRAPH
   (#xFA2C ?Ó›) ; CJK COMPATIBILITY IDEOGRAPH
   (#x999E ?Óﬁ) ; CJK UNIFIED IDEOGRAPH
   (#x9A4E ?Óﬂ) ; CJK UNIFIED IDEOGRAPH
   (#x9AD9 ?Ó‡) ; CJK UNIFIED IDEOGRAPH
   (#x9ADC ?Ó·) ; CJK UNIFIED IDEOGRAPH
   (#x9B75 ?Ó‚) ; CJK UNIFIED IDEOGRAPH
   (#x9B72 ?Ó„) ; CJK UNIFIED IDEOGRAPH
   (#x9B8F ?Ó‰) ; CJK UNIFIED IDEOGRAPH
   (#x9BB1 ?ÓÂ) ; CJK UNIFIED IDEOGRAPH
   (#x9BBB ?ÓÊ) ; CJK UNIFIED IDEOGRAPH
   (#x9C00 ?ÓÁ) ; CJK UNIFIED IDEOGRAPH
   (#x9D70 ?ÓË) ; CJK UNIFIED IDEOGRAPH
   (#x9D6B ?ÓÈ) ; CJK UNIFIED IDEOGRAPH
   (#xFA2D ?ÓÍ) ; CJK COMPATIBILITY IDEOGRAPH
   (#x9E19 ?ÓÎ) ; CJK UNIFIED IDEOGRAPH
   (#x9ED1 ?ÓÏ) ; CJK UNIFIED IDEOGRAPH
   (#x2170 ?ÓÔ) ; SMALL ROMAN NUMERAL ONE
   (#x2171 ?Ó) ; SMALL ROMAN NUMERAL TWO
   (#x2172 ?ÓÒ) ; SMALL ROMAN NUMERAL THREE
   (#x2173 ?ÓÚ) ; SMALL ROMAN NUMERAL FOUR
   (#x2174 ?ÓÛ) ; SMALL ROMAN NUMERAL FIVE
   (#x2175 ?ÓÙ) ; SMALL ROMAN NUMERAL SIX
   (#x2176 ?Óı) ; SMALL ROMAN NUMERAL SEVEN
   (#x2177 ?Óˆ) ; SMALL ROMAN NUMERAL EIGHT
   (#x2178 ?Ó˜) ; SMALL ROMAN NUMERAL NINE
   (#x2179 ?Ó¯) ; SMALL ROMAN NUMERAL TEN
   (#xFFE2 ?Ó˘) ; FULLWIDTH NOT SIGN
   (#xFFE4 ?Ó˙) ; FULLWIDTH BROKEN BAR
   (#xFF07 ?Ó˚) ; FULLWIDTH APOSTROPHE
   (#xFF02 ?Ó¸) ; FULLWIDTH QUOTATION MARK
   ;; not support IBM extension characters 
 ))
